### ISSUE TITLE
Panic while sync of node group with status - Create failed

### ISSUE THREAD

**Issue by cpinjani** [rancher/eks-operator#169]
**Rancher Server Setup**
Rancher version: 2.7-head - fbca7c3
Installation option: Helm Chart
If Helm Chart, Kubernetes Cluster and version: EKS 1.25

**Information about the Cluster**
Kubernetes version: EKS with Kubernetes 1.25
Cluster Type (Downstream): Hosted = EKS

**User Information**
What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) - Admin

**Describe the bug**
Rancher is crashing while syncing with AWS of node group with status of Create failed

**To Reproduce**
- Add valid AWS cloud credentials
- Provision downstream EKS cluster with nodegroup with Rancher created Launch template for nodes & t3.large instance type
- On AWS console, add new nodegroup with nodes using above launch template's Default version 1 (not latest version)
- Node group creation fails on AWS, on next sync Rancher crashes

**Logs**
```
2023-05-29T10:39:13.278461607Z 2023/05/29 10:39:13 [INFO] checking cluster [c-mc9lr] upstream state for changes
2023-05-29T10:39:14.330149095Z 2023/05/29 10:39:14 [INFO] cluster [c-mc9lr] matches upstream, skipping spec sync
2023-05-29T10:44:14.278471912Z 2023/05/29 10:44:14 [INFO] checking cluster [c-mc9lr] upstream state for changes
2023-05-29T10:44:15.346803789Z 2023/05/29 10:44:15 [INFO] cluster [c-mc9lr] matches upstream, skipping spec sync
2023-05-29T10:49:15.279370474Z 2023/05/29 10:49:15 [INFO] checking cluster [c-mc9lr] upstream state for changes
2023-05-29T10:49:16.355974571Z 2023/05/29 10:49:16 [INFO] cluster [c-mc9lr] matches upstream, skipping spec sync
2023-05-29T10:54:16.278451114Z 2023/05/29 10:54:16 [INFO] checking cluster [c-mc9lr] upstream state for changes
2023-05-29T10:54:17.323399780Z 2023/05/29 10:54:17 [INFO] cluster [c-mc9lr] matches upstream, skipping spec sync
2023-05-29T10:59:17.271275337Z 2023/05/29 10:59:17 [INFO] checking cluster [c-mc9lr] upstream state for changes
2023-05-29T10:59:18.826879608Z E0529 10:59:18.826702      33 runtime.go:79] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
2023-05-29T10:59:18.826923005Z goroutine 5355 [running]:
2023-05-29T10:59:18.826929941Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x428e3a0?, 0xc0074b2dc8})
2023-05-29T10:59:18.826934975Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:75 +0x99
2023-05-29T10:59:18.826939771Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00deb6a90?})
2023-05-29T10:59:18.826944525Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:49 +0x75
2023-05-29T10:59:18.826948931Z panic({0x428e3a0, 0xc0074b2dc8})
2023-05-29T10:59:18.826954038Z  /usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
2023-05-29T10:59:18.826960880Z github.com/rancher/eks-operator/controller.BuildUpstreamClusterState({0xc00a4a4ee0, 0xc}, {0xc01982d488, 0x14}, 0xc011179618, {0xc0117c36d0, 0x2, 0xc00a4a4f79?}, {0x4fa5c80, 0xc00b9ad908}, ...)
2023-05-29T10:59:18.826966881Z  /go/pkg/mod/github.com/rancher/eks-operator@v1.2.1-rc3/controller/eks-cluster-config-handler.go:861 +0x1729
2023-05-29T10:59:18.826972822Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.BuildEKSUpstreamSpec({0x4f9ccf8?, 0xc00a145f80?}, 0xc0034eca80)
2023-05-29T10:59:18.826978467Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/eks_upstream_spec.go:83 +0x525
2023-05-29T10:59:18.826987235Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.getComparableUpstreamSpec({0x4f9ccf8, 0xc00a145f80}, {0x7fa430e02c60, 0xc00019f730}, 0xc0034eca80)
2023-05-29T10:59:18.826992305Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go:288 +0xec
2023-05-29T10:59:18.826996827Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.(*clusterRefreshController).refreshClusterUpstreamSpec(0xc005a07220, 0xc0034eca80, {0x45b2d0b, 0x3})
2023-05-29T10:59:18.827001264Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go:155 +0xd1
2023-05-29T10:59:18.827005685Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.(*clusterRefreshController).onClusterChange(0xc005a07220, {0xc00fb45e60, 0x7}, 0xc0034eca80)
2023-05-29T10:59:18.827010308Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go:79 +0x165
2023-05-29T10:59:18.827014755Z github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc00fb45e60?, 0x0?}, {0x4f75a68?, 0xc0034eca80?})
2023-05-29T10:59:18.827019430Z  /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
2023-05-29T10:59:18.827026065Z github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x4514280?, {0xc00fb45e60?, 0x4626c7d?}, {0x4f75a68?, 0xc0034eca80?})
2023-05-29T10:59:18.827030854Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedcontroller.go:29 +0x38
2023-05-29T10:59:18.827035753Z github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000d6e3c0, {0xc00fb45e60, 0x7}, {0x4f75a68, 0xc00a382a80})
2023-05-29T10:59:18.827040398Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedhandler.go:75 +0x23f
2023-05-29T10:59:18.827045367Z github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000e4c630, {0xc00fb45e60, 0x7})
2023-05-29T10:59:18.827050000Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:232 +0x93
2023-05-29T10:59:18.827070669Z github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000e4c630, {0x39a6ce0?, 0xc00deb6a90?})
2023-05-29T10:59:18.827075678Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:213 +0x105
2023-05-29T10:59:18.827081198Z github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000e4c630)
2023-05-29T10:59:18.827085961Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:190 +0x46
2023-05-29T10:59:18.827090760Z github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0043ef6a0?)
2023-05-29T10:59:18.827095466Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:179 +0x25
2023-05-29T10:59:18.827100555Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0a28326e?)
2023-05-29T10:59:18.827105380Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
2023-05-29T10:59:18.827110588Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x38737574617473?, {0x4f67880, 0xc00426c210}, 0x1, 0xc001339b00)
2023-05-29T10:59:18.827115298Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
2023-05-29T10:59:18.827133385Z k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xa646e756f662073?, 0x3b9aca00, 0x0, 0x54?, 0x1422001006a3d19b?)
2023-05-29T10:59:18.827139588Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
2023-05-29T10:59:18.827144575Z k8s.io/apimachinery/pkg/util/wait.Until(0x6874242a64657470?, 0x616974696e692065?, 0x2073656d616e206c?)
2023-05-29T10:59:18.827149867Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
2023-05-29T10:59:18.827155012Z created by github.com/rancher/lasso/pkg/controller.(*controller).run
2023-05-29T10:59:18.827159906Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:147 +0x2a7
2023-05-29T10:59:18.830401178Z panic: runtime error: index out of range [0] with length 0 [recovered]
2023-05-29T10:59:18.830422679Z  panic: runtime error: index out of range [0] with length 0
2023-05-29T10:59:18.830436773Z 
2023-05-29T10:59:18.830443958Z goroutine 5355 [running]:
2023-05-29T10:59:18.830449778Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00deb6a90?})
2023-05-29T10:59:18.830455640Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
2023-05-29T10:59:18.830460955Z panic({0x428e3a0, 0xc0074b2dc8})
2023-05-29T10:59:18.830465881Z  /usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
2023-05-29T10:59:18.830471711Z github.com/rancher/eks-operator/controller.BuildUpstreamClusterState({0xc00a4a4ee0, 0xc}, {0xc01982d488, 0x14}, 0xc011179618, {0xc0117c36d0, 0x2, 0xc00a4a4f79?}, {0x4fa5c80, 0xc00b9ad908}, ...)
2023-05-29T10:59:18.830477522Z  /go/pkg/mod/github.com/rancher/eks-operator@v1.2.1-rc3/controller/eks-cluster-config-handler.go:861 +0x1729
2023-05-29T10:59:18.830482562Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.BuildEKSUpstreamSpec({0x4f9ccf8?, 0xc00a145f80?}, 0xc0034eca80)
2023-05-29T10:59:18.830487640Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/eks_upstream_spec.go:83 +0x525
2023-05-29T10:59:18.830492466Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.getComparableUpstreamSpec({0x4f9ccf8, 0xc00a145f80}, {0x7fa430e02c60, 0xc00019f730}, 0xc0034eca80)
2023-05-29T10:59:18.830497365Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go:288 +0xec
2023-05-29T10:59:18.830502458Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.(*clusterRefreshController).refreshClusterUpstreamSpec(0xc005a07220, 0xc0034eca80, {0x45b2d0b, 0x3})
2023-05-29T10:59:18.830519214Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go:155 +0xd1
2023-05-29T10:59:18.830524923Z github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher.(*clusterRefreshController).onClusterChange(0xc005a07220, {0xc00fb45e60, 0x7}, 0xc0034eca80)
2023-05-29T10:59:18.830529821Z  /go/src/github.com/rancher/rancher/pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go:79 +0x165
2023-05-29T10:59:18.830535053Z github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc00fb45e60?, 0x0?}, {0x4f75a68?, 0xc0034eca80?})
2023-05-29T10:59:18.830539798Z  /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
2023-05-29T10:59:18.830544900Z github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x4514280?, {0xc00fb45e60?, 0x4626c7d?}, {0x4f75a68?, 0xc0034eca80?})
2023-05-29T10:59:18.830549981Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedcontroller.go:29 +0x38
2023-05-29T10:59:18.830554887Z github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000d6e3c0, {0xc00fb45e60, 0x7}, {0x4f75a68, 0xc00a382a80})
2023-05-29T10:59:18.830559665Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/sharedhandler.go:75 +0x23f
2023-05-29T10:59:18.830564310Z github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000e4c630, {0xc00fb45e60, 0x7})
2023-05-29T10:59:18.830569051Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:232 +0x93
2023-05-29T10:59:18.830573755Z github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000e4c630, {0x39a6ce0?, 0xc00deb6a90?})
2023-05-29T10:59:18.830578516Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:213 +0x105
2023-05-29T10:59:18.830583918Z github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000e4c630)
2023-05-29T10:59:18.830589085Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:190 +0x46
2023-05-29T10:59:18.830594238Z github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0043ef6a0?)
2023-05-29T10:59:18.830599133Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:179 +0x25
2023-05-29T10:59:18.830604091Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0a28326e?)
2023-05-29T10:59:18.830609038Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
2023-05-29T10:59:18.830614177Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x38737574617473?, {0x4f67880, 0xc00426c210}, 0x1, 0xc001339b00)
2023-05-29T10:59:18.830625830Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
2023-05-29T10:59:18.830631545Z k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xa646e756f662073?, 0x3b9aca00, 0x0, 0x54?, 0x1422001006a3d19b?)
2023-05-29T10:59:18.830637133Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
2023-05-29T10:59:18.830646011Z k8s.io/apimachinery/pkg/util/wait.Until(0x6874242a64657470?, 0x616974696e692065?, 0x2073656d616e206c?)
2023-05-29T10:59:18.830651251Z  /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
2023-05-29T10:59:18.830656007Z created by github.com/rancher/lasso/pkg/controller.(*controller).run
2023-05-29T10:59:18.830660908Z  /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230428185353-36908edf817b/pkg/controller/controller.go:147 +0x2a7

```
**Result**
Panic while syncing of node group with status - Create failed

**Screenshots**
![image](https://github.com/rancher/eks-operator/assets/73099870/d777b19c-a317-4c3d-ae47-0d523b939ab7)

**Comment by kkaempf** [comment]
Is this still happening ?

**Comment by cpinjani** [comment]
Yes, it is reproducible on:
```
eks-operator:v1.2.2-rc3
v2.7-10d02ae6827fd549ae0f373be84a5e327999925b-head
```

**Comment by salasberryfin** [comment]
When a Rancher-managed launch template is created for a new node group, the first version is created as a default placeholder as can be seen in https://github.com/rancher/eks-operator/blob/d7edb15ed3caaef99aeba31945fc8e2b3b04337a/pkg/eks/create.go#L186 and it is not a valid launch template. We need to fix the panic to avoid Rancher from breaking, though.

**Comment by salasberryfin** [comment]
PRs created to avoid panic when the launch template is malformed: rancher/eks-operator#232 and rancher/eks-operator#235

**Comment by cpinjani** [comment]
Validated as fixed on build:
```
eks-operator:v1.3.0-rc2
v2.8-a3aec3826e9e48f1c12ee0e04ae90e01bbd8b72f-head
```
**Steps**
- Provision downstream EKS cluster with nodegroup with Rancher created Launch template for nodes & t3.large instance type
- On AWS console, add new nodegroup with nodes using above launch template's Default version 1 (not latest version)
- Node group creation fails on AWS, on next sync Rancher **does not** crashes and provides useful error

_Rancher logs:_
```
2023/09/07 19:15:57 [ERROR] error syncing 'c-bvktk': handler eks-operator-controller: [Syncing error: syncing failed] launch template for node group [test1] in cluster [cpinjani-eks] is malformed, requeuing
2023/09/07 19:15:58 [ERROR] error syncing 'c-bvktk': handler eks-operator-controller: [Syncing error: syncing failed] launch template for node group [test1] in cluster [cpinjani-eks] is malformed, requeuing
2023/09/07 19:15:58 [ERROR] error syncing 'c-bvktk': handler eks-operator-controller: [Syncing error: syncing failed] launch template for node group [test1] in cluster [cpinjani-eks] is malformed, requeuing
2023/09/07 19:15:58 [ERROR] error syncing 'c-bvktk': handler eks-operator-controller: [Syncing error: syncing failed] launch template for node group [test1] in cluster [cpinjani-eks] is malformed, requeuing
2023/09/07 19:15:58 [ERROR] error syncing 'c-bvktk': handler eks-operator-controller: [Syncing error: syncing failed] launch template for node group [test1] in cluster [cpinjani-eks] is malformed, requeuing
```

![image](https://github.com/rancher/eks-operator/assets/73099870/c575e99b-6066-461d-8bc8-5c05c144abb4)
