### ISSUE TITLE
Segfault when creating node group with period in name

### ISSUE THREAD

**Issue by solocommand** [rancher/eks-operator#670]
Hello,

When creating a new node group within an EKS cluster config containing a period (such as `c7i-flex.us-east-2a`), the eks operator segfaults and then sits in a crash loop. This exists in both versions `1.3.2` and `1.9.0-rc.9`. Logs are included below:
```
time="2024-07-09T18:42:44Z" level=info msg="Starting eks.cattle.io/v1, Kind=EKSClusterConfig controller"
time="2024-07-09T18:42:44Z" level=info msg="Starting /v1, Kind=Secret controller"
E0709 18:42:45.351548       8 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 69 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d3c4c0?, 0x378d960})
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0006c6780?})
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1d3c4c0?, 0x378d960?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/rancher/eks-operator/pkg/eks.CreateNodeGroup(0xc0008e91a8)
	/go/src/github.com/rancher/eks-operator/pkg/eks/create.go:318 +0x9a7
github.com/rancher/eks-operator/controller.(*Handler).updateUpstreamClusterState(0xc000135480, 0xc000bb40f0, 0xc0004a7340, 0xc000a7a0c0, {0xc000b76cc0?, 0x32?}, 0xc000062268?)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:1092 +0xd4b
github.com/rancher/eks-operator/controller.(*Handler).checkAndUpdate(0xc000135480, 0xc0004a7340, 0xc000a7a0c0)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:373 +0xa97
github.com/rancher/eks-operator/controller.(*Handler).OnEksConfigChanged(0xc000135480, {0x0?, 0x0?}, 0xc0004a7340)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:99 +0x195
github.com/rancher/eks-operator/controller.Register.(*Handler).recordError.func1({0xc000045420?, 0x1a?}, 0xc0004a7340?)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:111 +0x37
github.com/rancher/wrangler/v2/pkg/generic.(*Controller[...].func1({0x2633d88?, 0xc0004a7340?})
	/go/pkg/mod/github.com/rancher/wrangler/v2@v2.1.3/pkg/generic/controller.go:169 +0x48
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0006d9c20?, {0xc000045420?, 0x200?}, {0x2633d88?, 0xc0004a7340?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/sharedcontroller.go:29 +0x32
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0004d8e60, {0xc000045420, 0x1a}, {0x2633d88, 0xc0004a7340})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/sharedhandler.go:75 +0x208
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0000aa630, {0xc000045420, 0x1a})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:232 +0x8d
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0000aa630, {0x1ba77c0?, 0xc0006c6780})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:213 +0xf7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0000aa630)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:190 +0x45
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:179
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006082d8?, {0x2627a00, 0xc000a747b0}, 0x1, 0xc0000c4300)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x100009920?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(0xc0000aa630?, 0x3?, 0xc0000c4300?)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:161 +0x1e
created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 62
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:147 +0x2d0
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xff2d07]
goroutine 69 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0006c6780?})
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x1d3c4c0?, 0x378d960?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/rancher/eks-operator/pkg/eks.CreateNodeGroup(0xc0008e91a8)
	/go/src/github.com/rancher/eks-operator/pkg/eks/create.go:318 +0x9a7
github.com/rancher/eks-operator/controller.(*Handler).updateUpstreamClusterState(0xc000135480, 0xc000bb40f0, 0xc0004a7340, 0xc000a7a0c0, {0xc000b76cc0?, 0x32?}, 0xc000062268?)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:1092 +0xd4b
github.com/rancher/eks-operator/controller.(*Handler).checkAndUpdate(0xc000135480, 0xc0004a7340, 0xc000a7a0c0)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:373 +0xa97
github.com/rancher/eks-operator/controller.(*Handler).OnEksConfigChanged(0xc000135480, {0x0?, 0x0?}, 0xc0004a7340)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:99 +0x195
github.com/rancher/eks-operator/controller.Register.(*Handler).recordError.func1({0xc000045420?, 0x1a?}, 0xc0004a7340?)
	/go/src/github.com/rancher/eks-operator/controller/eks-cluster-config-handler.go:111 +0x37
github.com/rancher/wrangler/v2/pkg/generic.(*Controller[...].func1({0x2633d88?, 0xc0004a7340?})
	/go/pkg/mod/github.com/rancher/wrangler/v2@v2.1.3/pkg/generic/controller.go:169 +0x48
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0006d9c20?, {0xc000045420?, 0x200?}, {0x2633d88?, 0xc0004a7340?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/sharedcontroller.go:29 +0x32
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0004d8e60, {0xc000045420, 0x1a}, {0x2633d88, 0xc0004a7340})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/sharedhandler.go:75 +0x208
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0000aa630, {0xc000045420, 0x1a})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:232 +0x8d
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0000aa630, {0x1ba77c0?, 0xc0006c6780})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:213 +0xf7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0000aa630)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:190 +0x45
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:179
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006082d8?, {0x2627a00, 0xc000a747b0}, 0x1, 0xc0000c4300)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x100009920?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(0xc0000aa630?, 0x3?, 0xc0000c4300?)
	/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/util/wait/backoff.go:161 +0x1e
created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 62
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20240123150939-7055397d6dfa/pkg/controller/controller.go:147 +0x2d0
```

**Comment by mjura** [comment]
@solocommand I have tried to reproduce this issue and I couldn't this error. Could you please provide us your config spec ?

Thank you,

**Comment by solocommand** [comment]
> @solocommand I have tried to reproduce this issue and I couldn't this error. Could you please provide us your config spec ?
> 
> Thank you,

Hmm, I'm no longer able to reproduce this either, I must have had some other issue at the time. I tried creating a node group just now with the name `c7i-flex.us-east-2a` and it logged the error as expected, instead of segfaulting:
```log
time="2024-07-30T15:39:02Z" level=error msg="error syncing 'cattle-global-data/c-h675r': handler eks-controller: error creating nodegroup: InvalidParameterException: The nodegroup name parameter contains invalid characters. It should conform to the regular expression \"^[0-9A-Za-z][A-Za-z0-9-_]*\"In other words, it should start with a number or letter, and can contain numbers, letters, dashes, and underscores.\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"9f415d21-86d5-45c9-bf6d-776dac6725c1\"\n  },\n  ClusterName: \"base-cms\",\n  Message_: \"The nodegroup name parameter contains invalid characters. It should conform to the regular expression \\\"^[0-9A-Za-z][A-Za-z0-9-_]*\\\"In other words, it should start with a number or letter, and can contain numbers, letters, dashes, and underscores.\",\n  NodegroupName: \"c7i-flex.us-east-2a\"\n}, requeuing"
```

Sorry!
