### ISSUE TITLE
[SURE-9393] Rancher crash looping (panic) after provisioning an EKS cluster

### ISSUE THREAD

**Issue by kkaempf** [rancher/eks-operator#950]
### Steps to reproduce:

Provision a new EKS cluster with all default settings. Under "Networking" choose "Select from existing subnets" and select two existing subnets from a pre-existing VPC.
Wait for the cluster to provision. 

Result:

After some time Rancher will crash with a panic.

The following error is logged in the Rancher pods (see attached log file):
 
~~~
E1119 21:15:45.659899 39 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference) goroutine 2549 [running]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x82a1c60, 0x100f0fa0}) /go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/runtime/runtime.go:75 +0x85 k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc009370750?}) /go/pkg/mod/k8s.io/apimachinery@v0.30.1/pkg/util/runtime/runtime.go:49 +0x6b panic({0x82a1c60?, 0x100f0fa0?}) /usr/lib64/go/1.22/src/runtime/panic.go:770 +0x132 github.com/rancher/rancher/pkg/controllers/management/eks.(*eksOperatorController).onClusterChange(0xc00461f500, {0x9c9d9e0?, 0xc0209b1b01?}, 0x46222d?) /app/pkg/controllers/management/eks/eks_cluster_handler.go:204 +0x8f8
~~~
 
 The Rancher pods will enter crash looping state and never recover again.

I exported the eksclusterconfig object for the provisioned cluster (see attachments).

**Comment by valaparthvi** [comment]
@thehejik  and I debugged this issue, and here is our observation.
 
Steps to reproduce: 

0. Provision rancher 2.9.4 from rancher-prime channel
1. Create an IAM user with all needed permissions for EKS
2. Create a custom IAM policy with full access to EKS but disable Read/EKS:DescribeAddon permission
3. Assign the custom made policy to the user + generate keys as credentials
4. Provision the cluster by using the credentials
5. Wait for the EKS:DescribeAddon permission error
6. Go to AWS and enable the EKS:DescribeAddon permission in your custom IAM policy
7. The cluster will report Waiting for API and once it is provisioned the rancher pod will crash

Note: 
1. With enabled EBS out of tree driver we were unable to reproduce it.
2. We did not use any custom VPC, just the one created by Rancher
3. We were able to reproduce the issue twice in a row

Tomas also found a way to resurrect Rancher instance by deleting the bad cluster using -
```
kubectl delete clusters.management.cattle.io <cluster-id>
```

This is where the panic comes from - https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/eks/eks_cluster_handler.go#L204

We are still figuring out the root cause.
